export const ratingTagsConfig = {
  'Household Work': {
    5: [
      '#polite',
      '#onTime',
      '#friendly',
      '#detailOriented',
      '#cleanWork',
      '#trustworthy',
    ],
    4: [
      '#goodWork',
      '#helpful',
      '#timely',
      '#organized',
      '#minorIssues',
      '#friendly',
    ],
    3: [
      '#average',
      '#neededReminder',
      '#acceptable',
      '#basicQuality',
      '#communicationGap',
    ],
    2: ['#late', '#unfinished', '#distracted', '#careless', '#lowEffort'],
    1: [
      '#unprofessional',
      '#veryLate',
      '#badBehaviour',
      '#poorQuality',
      '#notRecommended',
    ],
  },

  Cooking: {
    5: [
      '#deliciousFood',
      '#onTime',
      '#cleanKitchen',
      '#friendly',
      '#hygienic',
      '#creativeDishes',
    ],
    4: [
      '#goodTaste',
      '#timely',
      '#basicMenu',
      '#helpful',
      '#minorIssues',
      '#neatWork',
    ],
    3: [
      '#averageTaste',
      '#acceptable',
      '#limitedMenu',
      '#needsImprovement',
      '#okayExperience',
    ],
    2: [
      '#blandFood',
      '#lateDelivery',
      '#dirtyKitchen',
      '#slowService',
      '#lowQuality',
    ],
    1: [
      '#unhygienic',
      '#veryLate',
      '#badBehaviour',
      '#spoiledFood',
      '#notRecommended',
    ],
  },

  Plumbing: {
    5: [
      '#fixedLeak',
      '#quickResponse',
      '#professional',
      '#noMess',
      '#onTime',
      '#skilledWork',
    ],
    4: [
      '#goodFix',
      '#reliable',
      '#minorLeaksRemain',
      '#timely',
      '#cleanWork',
      '#helpful',
    ],
    3: [
      '#temporaryFix',
      '#average',
      '#needsImprovement',
      '#okayWork',
      '#basicRepair',
    ],
    2: ['#late', '#unskilled', '#leakReturned', '#poorTools', '#lowQuality'],
    1: [
      '#unprofessional',
      '#veryLate',
      '#badBehaviour',
      '#didNotFix',
      '#notRecommended',
    ],
  },

  'Security Guard': {
    5: [
      '#alert',
      '#punctual',
      '#trustworthy',
      '#disciplined',
      '#friendly',
      '#professional',
    ],
    4: [
      '#reliable',
      '#timely',
      '#helpful',
      '#attentive',
      '#organized',
      '#minorIssues',
    ],
    3: [
      '#averageAlertness',
      '#acceptable',
      '#basicDiscipline',
      '#needsImprovement',
      '#okayService',
    ],
    2: ['#distracted', '#late', '#unresponsive', '#lowAlertness', '#untrained'],
    1: [
      '#unprofessional',
      '#missingFromPost',
      '#badBehaviour',
      '#unsafe',
      '#notRecommended',
    ],
  },

  Cleaning: {
    5: [
      '#spotless',
      '#quickResponse',
      '#onTime',
      '#detailedCleaning',
      '#friendly',
      '#trustworthy',
    ],
    4: [
      '#goodWork',
      '#organized',
      '#helpful',
      '#timely',
      '#basicCleaning',
      '#minorIssues',
    ],
    3: [
      '#averageCleaning',
      '#acceptable',
      '#missedSpots',
      '#needsImprovement',
      '#okayWork',
    ],
    2: ['#late', '#careless', '#dirtyAfterWork', '#lowEffort', '#unfinished'],
    1: [
      '#unprofessional',
      '#veryLate',
      '#badBehaviour',
      '#poorCleaning',
      '#notRecommended',
    ],
  },

  'Construction & Skilled Labor': {
    5: [
      '#highQuality',
      '#skilled',
      '#onTime',
      '#hardWorking',
      '#safeWork',
      '#professional',
    ],
    4: [
      '#goodWork',
      '#reliable',
      '#timely',
      '#helpful',
      '#minorIssues',
      '#organized',
    ],
    3: [
      '#averageQuality',
      '#acceptable',
      '#needsImprovement',
      '#okayWork',
      '#basicSkills',
    ],
    2: ['#late', '#unskilled', '#messySite', '#unfinished', '#lowQuality'],
    1: [
      '#unprofessional',
      '#veryLate',
      '#badBehaviour',
      '#unsafeWork',
      '#notRecommended',
    ],
  },

  'General Manual Labor': {
    5: [
      '#hardWorking',
      '#onTime',
      '#friendly',
      '#quickLearner',
      '#reliable',
      '#energetic',
    ],
    4: [
      '#goodWork',
      '#helpful',
      '#timely',
      '#minorIssues',
      '#organized',
      '#reliable',
    ],
    3: [
      '#average',
      '#acceptable',
      '#slowPace',
      '#needsImprovement',
      '#okayWork',
    ],
    2: ['#late', '#lowEffort', '#unskilled', '#careless', '#unfinished'],
    1: [
      '#unprofessional',
      '#veryLate',
      '#badBehaviour',
      '#poorWork',
      '#notRecommended',
    ],
  },

  Other: {
    5: [
      '#professional',
      '#onTime',
      '#friendly',
      '#skilled',
      '#trustworthy',
      '#helpful',
    ],
    4: [
      '#goodWork',
      '#helpful',
      '#timely',
      '#organized',
      '#minorIssues',
      '#responsive',
    ],
    3: [
      '#average',
      '#acceptable',
      '#needsImprovement',
      '#okayWork',
      '#basicSkills',
    ],
    2: ['#late', '#lowEffort', '#unskilled', '#careless', '#unfinished'],
    1: [
      '#unprofessional',
      '#veryLate',
      '#badBehaviour',
      '#poorWork',
      '#notRecommended',
    ],
  },
};
